spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
  routes:
    - id: filme
      uri: lb://filme
      predicates:
        - Path=/filmes/**

    - id: aluguel
      uri: lb://aluguel
      predicates:
        - Path=/alugueis/**

    - id: cliente
      uri: lb://cliente
      predicates:
        - Path=/clientes/**

server:
  port: 8765

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
